apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    app: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: tricker14/user-management-service:1
          env:
          - name: PORT
            value: "8086"
          - name: DB_HOST
            value: "userdb-service.default"
          - name: DB_PORT
            value: "3306"
          - name: DB_USERNAME
            value: root
          - name: DB_ROOT_PASSWORD
            value: root
          - name: DB_PASSWORD
            value: root
          - name: DB_DATABASE
            value: vouUser