export const BRANDS_LOGO = [
    { src: "/Partnered_Brands_Logo/123phim.png", alt: "123phim" },
    { src: "/Partnered_Brands_Logo/bigo-live.png", alt: "bigo-live" },
    { src: "/Partnered_Brands_Logo/cgv.png", alt: "cgv" },
    { src: "/Partnered_Brands_Logo/coopmart.png", alt: "coopmart" },
    { src: "/Partnered_Brands_Logo/filmplus.vn.png", alt: "filmplus.vn" },
    { src: "/Partnered_Brands_Logo/game-ota.png", alt: "game-ota" },
    { src: "/Partnered_Brands_Logo/gogi-house.png", alt: "gogi-house" },
    { src: "/Partnered_Brands_Logo/hoayeuthuong.png", alt: "hoayeuthuong" },
    { src: "/Partnered_Brands_Logo/kichikichi.png", alt: "kichikichi" },
    { src: "/Partnered_Brands_Logo/lotte.png", alt: "lotte" },
    { src: "/Partnered_Brands_Logo/new-passio.png", alt: "new-passio" },
    { src: "/Partnered_Brands_Logo/smoothies-factory.png", alt: "smoothies-factory" },
    { src: "/Partnered_Brands_Logo/the-coffee-house.png", alt: "the-coffee-house" },
    { src: "/Partnered_Brands_Logo/tiki.png", alt: "tiki" },
    { src: "/Partnered_Brands_Logo/vetc.png", alt: "vetc" },
    { src: "/Partnered_Brands_Logo/vietjetair.png", alt: "vietjetair" },
    { src: "/Partnered_Brands_Logo/vtc-game.png", alt: "vtc-game" },
];