apiVersion: v1
kind: PersistentVolume
metadata:
  name: userdb-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data-user
    type: DirectoryOrCreate
---    
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS vouUser;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-pvc
spec:
  volumeName: userdb-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
