apiVersion: v1
kind: PersistentVolume
metadata:
  name: admindb-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
---    
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS vouAdmin;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admindb-pvc
spec:
  volumeName: admindb-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
